spring.application.name=bdmovies

# Configuracion H2
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Configuracion Oracle
spring.datasource.url=jdbc:oracle:thin:@jg8zehmxmjj2kb16_low
spring.datasource.username=ADMIN
spring.datasource.password=WingGundam333
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=C:\\Users\\corte\\OneDrive\\Escritorio\\microservicios\\s4\\Walleta_BDMovies

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

